title: Qwerty
description: Sholes and Glidden typewriter
quran:
  language_list:
    de_aburida:
      english_name: Abu Rida
      translator: Abu Rida Muhammad ibn Ahmad ibn Rassoul
      language: German
      source: Tanzil.net
      dir: /trans/de_aburida
    en_sahih:
      english_name: Sahen International
      translator: Saheeh International
      language: English
      source: Tanzil.net
      dir: /trans/en_sahih
    tr_yildirim:
      english_name: Çeviriyazı
      translator: Muhammet Abay
      language: Turkish
      source: Tanzil.net
      dir: /trans/tr_yildirim
